export default {
  default: '/',
  home: 'home',
  login: 'login',
  event: 'events',
  profile: 'profile',
  general: 'general',
  auth: 'auth',
  account: 'account',
  setting: 'settings',
  notification: 'notification',
  lang: 'lang',
  reservations: 'reservations',
  reservationDetail: 'reservations/:id',
  actions: 'actions',
  guests: 'guests',
  travelDates: 'dates',
  extras: 'extras',
  folio: 'folio',
  invoices: 'invoices',
  RENEW: '/auth/renew-token',

  //account
  properties: 'properties',
  propertyCreate: 'properties/create',
  attributes: 'attributes',
  services: 'services',
  type: 'type',
  list: 'list',
  create: 'create',
  duplicate: 'duplicate',
  payment: 'payment',
  users: 'users',
  userDetail: 'users/:id',
  tags: 'tags',
  tagDetail: 'tags/:id',
  media: 'media',
  activities: 'activities',
  landscapes: 'landscapes',
  vouchers: 'vouchers',
  holidayPackage: 'holiday-package',
  buildProcess: 'build-process',
  function: 'function',
  roomCategory: 'room-category',
  offer: 'offers',
  offerDetail: 'offers/:id',
  advertising: 'advertising',
  newsletter: 'newsletter',

  // property
  propertyCode: ':code',
  id: ':id',
  detail: 'detail',
  propertySetting: ':id/setting',
  rates: 'rates',
  ratePlans: 'rate-plans',
  inventory: 'inventory',
  unitGroups: 'unit-groups',
  unitGroupsDetail: 'unit-groups/:id',
  units: 'units',
  unitDetail: 'units/:id',
  prices: 'prices',
  bundles: 'bundles',
  bundlesOverview: 'overview',
  bundlesTemplate: 'template',
  bundlesNewsletter: 'newsletter',
  tasks: 'tasks',
  booker: 'booker',
  bookings: 'bookings',
  policies: 'policies',
  policyDetail: 'policies/:id',
  cancellation: 'cancellation',
  noShow: 'no-show',
  availability: 'availability',
  bundlesArchive: 'archive',

  //external pages
  ynrg12i19zq2x: 'ynrg12i19zq2x',
  h5dz2i81gu1m5: 'h5dz2i81gu1m5'
};

export const IBE_BOOKING_LINK_OFFER = 'https://ibe.bookinghms.com/booking/offer';
export const IBE_BOOKING_LINK_NEWSLETTER = 'https://ibe.bookinghms.com/booking/bundle';
